py_test(
    name = "test_get_graph",
    srcs = ["test_get_graph.py"],
    deps = [
        "//cli/bitcode:commands",
        "//cli/common:service_configuration_handler",
        "//cli/eesi:domain_knowledge_handler",
        "//cli/getgraph:commands",
        "//cli/test/common",
    ],
)
