py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "//cli/bitcode:args",
        "//cli/checker:args",
        "//cli/eesi:args",
        "//cli/embedding:args",
        "//cli/getgraph:args",
        "//cli/walker:args",
    ],
)
