py_library(
    name = "common",
    srcs = ["common.py"],
    data = [
        "//:cli_testdata_bitcode",
        "//bitcode:main",
        "//checker:main",
        "//eesi:main",
        "//getgraph:main",
    ],
    visibility = [
        "//visibility:public",
    ],
)
